addSbtPlugin("ch.epfl.scala"   % "sbt-bloop"       % "1.4.1")
addSbtPlugin("com.geirsson"    % "sbt-ci-release"  % "1.5.3")
addSbtPlugin("com.eed3si9n"    % "sbt-buildinfo"   % "0.9.0")
addSbtPlugin("org.wartremover" % "sbt-wartremover" % "2.4.9")
addSbtPlugin("org.scoverage"   % "sbt-scoverage"   % "1.6.0")
