addSbtPlugin("ch.epfl.scala"   % "sbt-bloop"       % "1.3.2")
addSbtPlugin("com.geirsson"    % "sbt-ci-release"  % "1.2.6")
addSbtPlugin("com.eed3si9n"    % "sbt-buildinfo"   % "0.9.0")
addSbtPlugin("org.wartremover" % "sbt-wartremover" % "2.4.2")
addSbtPlugin("com.github.sbt"  % "sbt-jacoco"      % "3.2.0")
